// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2bNrrfI0U9DvtRaXw9Lpxqys8_319BqU',
    appId: '1:943669126284:web:c584ca6af2e655557e87a9',
    messagingSenderId: '943669126284',
    projectId: 'rjpolicehackathon',
    authDomain: 'rjpolicehackathon.firebaseapp.com',
    storageBucket: 'rjpolicehackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxoGfrty6QsmwnkeKkkkqto5QIQaVD0mM',
    appId: '1:943669126284:android:0f26b9b378667ea17e87a9',
    messagingSenderId: '943669126284',
    projectId: 'rjpolicehackathon',
    storageBucket: 'rjpolicehackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlEFtUOJOMxUFWhNxcAS-XqW_Y8zQ-1LM',
    appId: '1:943669126284:ios:58142e20802651527e87a9',
    messagingSenderId: '943669126284',
    projectId: 'rjpolicehackathon',
    storageBucket: 'rjpolicehackathon.appspot.com',
    iosBundleId: 'com.example.circuitslingers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlEFtUOJOMxUFWhNxcAS-XqW_Y8zQ-1LM',
    appId: '1:943669126284:ios:eb45ffb8c0d819757e87a9',
    messagingSenderId: '943669126284',
    projectId: 'rjpolicehackathon',
    storageBucket: 'rjpolicehackathon.appspot.com',
    iosBundleId: 'com.example.circuitslingers.RunnerTests',
  );
}
